# Generated by Django 4.2.7 on 2023-11-30 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicelocation",
            name="zipcode",
            field=models.IntegerField(
                default="00000",
                help_text="Enter the zipcode",
                validators=[django.core.validators.MinLengthValidator(5)],
                verbose_name="ZipCode",
            ),
        ),
    ]
