# Generated by Django 4.2.7 on 2023-11-30 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("default_event_value", models.IntegerField()),
                (
                    "device_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device.devicemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_value", models.IntegerField()),
                (
                    "time_stamp",
                    models.DateTimeField(auto_now=True, verbose_name="TimeStamp"),
                ),
                (
                    "enrolled_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device.enrolleddevice",
                    ),
                ),
                (
                    "model_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device.modelevent",
                    ),
                ),
            ],
        ),
    ]
