# Generated by Django 4.2.7 on 2023-12-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0002_modelevent_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyprice",
            name="time_stamp",
            field=models.DateTimeField(verbose_name="TimeStamp"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="time_stamp",
            field=models.DateTimeField(verbose_name="TimeStamp"),
        ),
    ]
