# Generated by Django 4.2.7 on 2023-12-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0003_alter_energyprice_time_stamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolleddevice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
